backend:
  name: git-gateway
  branch: main
media_folder: "source/images/photos"
public_folder: "/images/photos"
collections:
  - name: "photos"
    label: "Photos"
    folder: "source/content/photos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}