---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: source/content/diary
  label: Diary
  create: documents
  match: "*.md"
  templates:
  - diary-post
upload_dir: source/images/photos
public_path: "/images/photos"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
